name = "careers-hive-malta"
compatibility_date = "2024-01-04"
pages_build_output_dir = ".next"

[[vars]]
key = "NEXT_PUBLIC_SUPABASE_URL"
value = "https://dxypolvymzoadprwgwfc.supabase.co"

[[vars]]
key = "NEXT_PUBLIC_SUPABASE_ANON_KEY"
value = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4eXBvbHZ5bXpvYWRwcndnd2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI4MjE5MDYsImV4cCI6MjA0ODM5OTkwNn0.4Y6QQBRx8PGnPoPq3r_lqdgUEDRwD6J5XEIOhQ7u8Rk"

[[vars]]
key = "SUPABASE_SERVICE_ROLE_KEY"
value = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4eXBvbHZ5bXpvYWRwcndnd2ZjIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMjgyMTkwNiwiZXhwIjoyMDQ4Mzk5OTA2fQ.iwD-xlPvzWC3O3HDl8v8mgwVBU_YeM4Aftz55HBnQbM"

[[vars]]
key = "NEXT_PUBLIC_SITE_URL"
value = "https://careers-hive-malta.pages.dev"
